version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_volume:/app
      - "./.config/git/.gitconfig:/root/.gitconfig"
      - "./.config/ssh:/root/.ssh"
    ports:
      - 80:15679
    tty: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend_volume:/app
      - uploader_volume:/usr/src/uploaded-images
      - "./.config/git/.gitconfig:/root/.gitconfig"
      - "./.config/ssh:/root/.ssh"
    tty: true
  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    volumes:
      - notification_volume:/app
      - "./.config/git/.gitconfig:/root/.gitconfig"
      - "./.config/ssh:/root/.ssh"
    ports:
      - 9261:9261
    tty: true
  backend_webserver:
    build:
      context: ./backend_webserver
      dockerfile: Dockerfile
    volumes: 
      - uploader_volume:/usr/src/uploaded-images
      - ./backend_webserver/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9262:80
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - database_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lunchtote
      POSTGRES_PASSWORD: dbpassword
  fixture:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - fixture_volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: lunchtote_fixture
      POSTGRES_PASSWORD: dbpassword
  store:
    image: redis:latest
    ports:
      - 6379:6379
  pubsub:
    image: redis:latest
    ports:
      - 6380:6379
     

volumes:
  frontend_volume:
  backend_volume:
  uploader_volume:
  notification_volume:
  database_volume:
  fixture_volume: